[tools]
uv = "latest"
ruff = "latest"
java = "zulu-21"
go = "latest"
ty = "latest"
prek = "latest"
python = "3.14.3"

[settings]
python.uv_venv_auto = true
trusted_config_paths = [
  "~/Developer/"
]
